# Generated by Django 4.1.3 on 2022-12-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_category_alter_animal_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Питомец', 'verbose_name_plural': 'Питомцы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
